---
title: "STOR 831 Course description"
author: "Shankar Bhamidi"
date: 2017-09-10
categories: ["Course Description"]
tags: ["Fall 2017"]
---


## Course overview

One of the central themes in both the theory and application of probability is understanding asymptotics of a sequence of random objects `$\{X_n:n\geq 1\}$` as `$n\to\infty$`. In undergraduate probability as well as a first  graduate level course in probability, much of the emphasis is on real valued random variables. As we progresses towards the forefront of research, we come across much more complicated objects including:

- Random objects in function space representing empirical processes derived from a sequence of observations  or lengths of queues. 
- Random probability measures representing the spectral distribution of a large random matrix 
- Random metric spaces describing large trees (e.g. phylogenetic trees or the minimal spanning tree) or network models in probabilistic combinatorics.   

Coupled with the above examples, in the last decade a new notion of convergence called  *Local weak convergence* has started to play a fundamental role in the probabilistic study of a wide range of problems. The main idea is as follows: When studying large discrete structures (for example a graphical model on a large graph), if we study "local neighborhoods" of a uniformly chosen random vertex, this converges to a local neighborhood of an infinite (model dependent) random structure. This ``local convergence'' is amazingly enough to understand asymptotics for global functionals such as the partition function of graphical models or the spectral distribution of the adjacency matrix of a random graph.  This technique has been used to great effect in a number of areas including compressed sensing, high-dimensional statistics,  combinatorial optimization, and statistical physics. 

## Topics covered

### Core Theory

The first aim of this course is to understand general probability theory for convergence of sequences of random objects in nice enough spaces. To start with we will largely follow [Billingsley's book on Weak convergence](http://search.lib.unc.edu/search?R=UNCb2554346). Topics that will be covered include:

- General theory of weak convergence.
- Special cases: `$\mathbb{R},\; \mathbb{R}^{\infty}$` and `$C[0,1]$`. Specialized techniques in `$\mathbb{R}$` including the method of moments and Stein's method. 
- Continuous mapping theorem. 
- Prokhorov's theorem and relative compactness. Skorohod representation theorem. 
- Analysis of `$C[0,1]$`. Introduction to Brownian motion and related processes (including the Brownian bridge). 
- Martingale functional central limit theorem. Applications in probabilistic combinatorics and applied probability. 
- A brief introduction to `$D[0,1]$`.  
- *If time permits:* A quick introduction to empirical processes theory.
- *If time permits:* Basic convergence results to other processes including Levy type processes.  
- *If time permits:* Wigner's semi-circular law and random matrices. 


This page was last updated on `r Sys.time()` Eastern Time.
